<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page { margin: 20px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #333; font-size: 24px; }
        .header .subtitle { color: #666; font-size: 14px; margin-top: 5px; }
        .info { margin-bottom: 20px; }
        .info table { width: 100%; border-collapse: collapse; }
        .info table td { padding: 5px; border: 1px solid #ddd; }
        .info table .label { font-weight: bold; background-color: #f5f5f5; width: 120px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table th { background-color: #4361ee; color: white; padding: 8px; text-align: left; font-size: 11px; }
        .table td { padding: 6px; border: 1px solid #ddd; font-size: 11px; }
        .table tr:nth-child(even) { background-color: #f9f9f9; }
        .total-row { font-weight: bold; background-color: #e8f4fd !important; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #ddd; padding-top: 10px; }
        .category-color { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 5px; vertical-align: middle; }
        .amount { text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="subtitle">Generated on: {{ $exportDate }}</div>
    </div>
    
    <div class="info">
        <table>
            <tr>
                <td class="label">User:</td>
                <td>{{ $user->name }} ({{ $user->email }})</td>
            </tr>
            <tr>
                <td class="label">Period:</td>
                <td>
                    @if($filters['start_date'] || $filters['end_date'])
                        {{ $filters['start_date'] ?? 'Start' }} to {{ $filters['end_date'] ?? 'End' }}
                    @else
                        All time
                    @endif
                </td>
            </tr>
            <tr>
                <td class="label">Category:</td>
                <td>{{ $filters['category'] }}</td>
            </tr>
            <tr>
                <td class="label">Total Records:</td>
                <td>{{ $expenses->count() }}</td>
            </tr>
        </table>
    </div>
    
    @if($expenses->count() > 0)
    <table class="table">
        <thead>
            <tr>
                <th style="width: 10%;">Date</th>
                <th style="width: 30%;">Description</th>
                <th style="width: 25%;">Category</th>
                <th style="width: 15%;" class="amount">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($expenses as $expense)
            <tr>
                <td>{{ $expense->date->format('Y-m-d') }}</td>
                <td>{{ $expense->description ?: '-' }}</td>
                <td>
                    @if($expense->category)
                        <span class="category-color" style="background-color: {{ $expense->category->color }}"></span>
                        {{ $expense->category->name }}
                    @else
                        Uncategorized
                    @endif
                </td>
                <td class="amount">${{ number_format($expense->amount, 2) }}</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="3" class="amount"><strong>Total:</strong></td>
                <td class="amount"><strong>${{ number_format($totalAmount, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>
    @else
    <div style="text-align: center; padding: 40px; color: #666;">
        No expenses found for the selected filters.
    </div>
    @endif
    
    <div class="footer">
        <p>Generated by finTrack &copy; {{ date('Y') }} | Page <span class="pageNumber"></span> of <span class="totalPages"></span></p>
    </div>
    
    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 10;
            $font = $fontMetrics->get_font("sans-serif");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 35;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>
</html>
